#   Numpy

## Question 1

### Arrays




You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

In [1]:
import numpy as np
def arrays(arr) :
    # arr[::-1] = to reverse the list
    # numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0) -> ndarray
    l = np.array(arr[::-1] ,float)
    return l

# string.strip([chars])->Returns a copy of the string with both leading and trailing characters removed.
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Question 2

### Shape and Reshape


You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.



In [2]:
# map(fun , exp) -> a map object
l =list(map(int , input().split()))
# numpy.reshape(a, newshape, order='C') -> ndarray
print(np.reshape(l,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## QUestion 3

### Transpose and Flatten



- You are given a   __N*M__ integer array matrix with space separated elements (N = rows and M  = columns).
- Your task is to print the transpose and flatten results.

In [3]:
import numpy as np
#str.split(separator, maxsplit) -> list
n =int(input().split()[0])
l = []

for i in range(n):
    l.append(list(map(int , input().split())))

l = np.array(l)
# numpy.transpose(a, axes=None) -> ndarray
print((l.transpose()))
# ndarray.flatten(order='C') ->ndarray
print((l.flatten()))

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Question 4

### Concatenate



- You are given two integer arrays of size  __N * P__ and  __M * P__ (**N***  &  **M** are  **P** rows, and  is the column). Your task is to concatenate the arrays along axis  __0__ .

In [4]:
import numpy as np
n , m , p = input().split()
# range(start , end , inc_val)
a = [list(map(int , input().split())) for i in range(int(n))]
a = np.array(a)
b = [list(map(int , input().split())) for i in range(int(m))]
b = np.array(b)
# numpy.concatenate((a1, a2, ...), axis=0, out=None) -> ndarray
print (np.concatenate((a, b), axis=0))  

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Question 5

### Zeros and Ones




You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones

In [7]:
n = list(map(int, input().split()))
# numpy.zeros(shape, dtype=float, order='C') -> ndarray
print(np.zeros(n, int))
# numpy.ones(shape, dtype=None, order='C') -> ndarray
print(np.ones(n, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Question 6

### Eye and Identity



Your task is to print an array of size __N * M__ with its main diagonal elements as __1's__ and __0's__ everywhere else.



In [8]:
"""
l = list(map(int, input().split()))
print(np.eye(l[0],l[1]))
"""
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C') - ndarray of shape (N,M)
print(str(np.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Question 7

### Array Mathematics



You are given two integer arrays, **A** and **b** of dimensions **N*M**.
Your task is to perform the following operations:
1. add **(A + B)**
2. Subtract **(A - B)**
3. Multiply **(A * B)**
4. Integer Division **(A /B )**
5. Mod **( A % B )**
6. Power **( A ** B )

In [9]:

n , m = map(int , input().split())
a = np.array([list(map(int, input().split())) for n in range(n)])
b = np.array([list(map(int, input().split())) for n in range(n)])
# add
print( a + b )
# sub
print( a - b )
# multuply
print( a * b )
# division
print( a // b)
# mod
print( a %  b)
# power
print( a ** b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Question 8

### Floor, Ceil and Rint



You are given a 1-D array, __A__ . Your task is to print the **Floor**, **Rint** and **Ciel** of all the elements of .



In [10]:
A = np.array(input().split(), float)

# numpy.floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])->ndarray
print (np.floor(A))

# numpy.ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])->ndarray
print (np.ceil(A))
# numpy.rint(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])->ndarray
print (np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


## Question 9

### Sum and Prod



- You are given a 2-D array with dimensions **N * M**.
- Your task is to perform the **sum** tool over axis __0__ and then find the **product** of that result.



In [11]:
n , m =  map(int, input().split())
a = np.array([input().split() for _ in range(n)], int)

# numpy.prod(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>) ->ndarray
print(np.prod(np.sum(a, axis=0), axis=0))


2 2 
1 2 
3 4
24


## Question 10

### Min and Max



- You are given a 2-D array with dimensions **N * M**.
- Your task is to perform the min function over axis __1__ and then find the max of that.

In [12]:
n , m = map(int ,input().split())
a = np.array([input().split() for i in range(n)] , int)

# ndarray.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True) ->int  maximum number
# ndarray.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True) ->int  minimum number
print(np.max(np.min(a , axis =1)))

4 2
2 5
3 7
2 3
4 0
3


## Question 11

### Mean, Var, and Std



 You are given a 2-D array of size **N * M**.
Your task is to find:

1. The mean along axis __1__
2. The var along axis __0__
3. The std along axis **None**

In [14]:
n,m = map(int, input().split())
b = [list(map(int, input().split())) for i in range(n)]
b = np.array(b)
# numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>) -> ndarray,
print(np.mean(b, axis = 1))
# numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>) -> ndarray,
print(np.var(b, axis = 0))
# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>) -> ndarray,
print(np.std(b))


2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


## Question 12

### Dot and Cross



You are given two arrays  **A** and **B**. Both have dimensions of **N * N**.
Your task is to compute their matrix product.

In [15]:
n = int(input())
a = np.array([input().split() for i in range(n)], int)
b = np.array([input().split() for i in range(n)], int)
# numpy.dot(a, b, out=None) -> ndarray
print(np.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Question 13

### Inner and Outer



- You are given two arrays  A and B.
- Your task is to compute their inner and outer product.

In [16]:
A = np.array(input().split() , int)
B = np.array(input().split()  ,int)
# numpy.inner(a, b) - > ndarray
print(np.inner(A, B))
# numpy.outer(a, b, out=None) - > ndarray
print(np.outer(A, B))

0 1
2 3
3
[[0 0]
 [2 3]]


## Question 14

### Polynomials



- You are given the coefficients of a polynomial **P**.
- Your task is to find the value of P  at point  **X**  .

In [17]:
import numpy as np

p= np.array(input().split() , float)
# numpy.polyval(p, x) -> ndarray or poly1d
print(np.polyval(p , int(input())))

1.1 2 3
0
3.0


## Question 15

### Linear Algebra



- You are given a square matrix  with A  dimensions  __N * M__ Your task is to find the determinant. 
- **Note** : Round the answer to 2 places after the decimal.

In [18]:
import numpy as np
n = int(input())
# numpy.linalg.det(a) -> array_like
print( round(np.linalg.det([list(map(float  , input().split())) for i in range(n)])   , 2 ))


2
1.1 1.1
1.1 1.1
0.0


#         Debugging

## Question 1

### Words score

In [19]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        else:
            score += 1
    return score


n = int(input())
words = input().split()
print(score_words(words))

3
programming is awesome
4


## Question 2

### Default Arguments



In [20]:
class EvenStream(object):
    def __init__(self):
        self.current = 0

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return

class OddStream(object):
    def __init__(self):
        self.current = 1

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return
## make it as a default  argument
def print_from_stream(n, stream= None):
    if not stream :
         stream = EvenStream()
    for _ in range(n):
        print(stream.get_next())


queries = int(input())
for _ in range(queries):
    stream_name, n = input().split()
    n = int(n)
    if stream_name == "even":
        print_from_stream(n)
    else:
        print_from_stream(n, OddStream())


3
odd 2 
1
3
even 3 
0
2
4
odd 5
1
3
5
7
9
